### ISSUE TITLE
Light Theme

### ISSUE THREAD

**Issue by yuriizinets** [peymanslh/vscode-blueberry-dark-theme#1]
Light theme, based on this setup.

Something like this, but normal :D
I don't really good in such things, so, I hope you not left the project.
I like themes with dark sidebar and light editor. Slack Theme is a nice example. I think it would be nice to provide optional dark sidebar for light setup.

![image](https://user-images.githubusercontent.com/17050536/43357546-9d313312-9283-11e8-8328-d8f07776a9b5.png)

Thank you for nice theme!

**Comment by peymanslh** [comment]
Hi @yzinets 
Sorry, I don't have enough time to create a light version.
If you want to, feel free to send a PR!
