### ISSUE TITLE
page background color not consistent

### ISSUE THREAD

**Issue by uladkasach** [peymanslh/vscode-blueberry-dark-theme#2]
Hey there!

First - huge thank you for creating this theme. Its brilliant. Really calming, really minimal, yet somehow makes everything still very distinct.

--

This may be something specific to my machine, but i was seeing that the background color on the text pages is not consistent (and changes as you scroll up and down): 
![image](https://user-images.githubusercontent.com/10381896/84146784-d9075300-aa21-11ea-9092-2a77edd2ecc9.png)

Here is one example of it not being consistent:
before selecting a line over it:
![image](https://user-images.githubusercontent.com/10381896/84146816-e4f31500-aa21-11ea-9720-073751efafbf.png)
after selecting the line in that area:
![image](https://user-images.githubusercontent.com/10381896/84146894-09e78800-aa22-11ea-81bc-1ba069709299.png)

You can see how the background changes from a darker color to a lighter color.

Do you have any idea what can be causing this?

**Comment by uladkasach** [comment]
```

  "workbench.colorCustomizations": {
    "[Blueberry dark theme]": {
      "widget.shadow": "#00000000",
		"input.background": "#ffffff00",
		"editor.selectionBackground": "#717cb400",
    "editor.selectionHighlightBackground": "#53a69700",
    "editorHoverWidget.border": "#ffffff00",
		"scrollbarSlider.background": "#00000000",
		"scrollbarSlider.hoverBackground": "#00000000",
    "peekView.border": "#00000000",
    "editorSuggestWidget.selectedBackground": "#00000000",
  }
}
```

Unfortunately, i've not had any luck. And am shooting in the dark :P 

This same problem occurs if i change the `editor.background` to any color that is not grayscale :/

**Comment by uladkasach** [comment]
Looks like this is a known Linux issue! https://github.com/microsoft/vscode/issues/85452

solved it by the answer in there.

thank you again for creating this great theme :)

**Comment by peymanslh** [comment]
Thanks, I'm very glad you chose it.  
@uladkasach
