### ISSUE TITLE
Change white color  

### ISSUE THREAD

**Issue by ibandim123** [peymanslh/vscode-blueberry-dark-theme#4]
Hi! Everything alright?

 Hi, I enjoy very much of your theme! I already use in my workspace and in my job! I want create new branch for introduce new color in white tags, if you permited, of course!

Att, Isaac.

**Comment by peymanslh** [comment]
Hi, Isaac!
I created a `dev` branch, feel free to send any PR for it.
Thanks!

**Comment by ibandim123** [comment]
Oh! Thanks Peyman. I certainly go used! Have good week.

Att, Isaac

Obter o Outlook para Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by ibandim123** [comment]
Hi Peyman!! Everything alright?

  Do you can give me access for file uploads in Dev branch?
  
I tried test my modd in VS code, but is no debug JSON anymore. If you know any platform in which i can view mod! I will enjoy.

**Comment by peymanslh** [comment]
Dear Isaac!
You can fork the repo and make your own branch and send a pull request to merge with `dev`.
If you're not familiar with the process you can read this article. [Link](https://docs.github.com/en/get-started/quickstart/fork-a-repo)
And please read this section to develop and test the theme. [Link](https://css-tricks.com/creating-a-vs-code-theme/#test-drive)

**Comment by ibandim123** [comment]
Hi Peyman, everything alright??

  I have done my moddifications and waiting an merge 1 commit into peymanslh:dev from ibandim123:dev.  I hope you like that! 👍, Thanks Payman!

Att, Isaac Costa
